import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed flex h-full w-full bg-slate-800 text-white">
          <div className="max-w-[300px] w-full border-r-4 border-r-slate-700 h-full flex flex-col justify-between">
            <Sidebar />
          </div>
          <div className="w-full grow-2 scroll-smooth overflow-y-scroll overflow-x-hidden">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
